### ISSUE TITLE
Not seem to work on MacOS BigSur

### ISSUE THREAD

**Issue by luv4ever2shail** [mikededo/dartBarrelFileGenerator#1]
On click. Seems to not do anything.
Tried out both options. Neither one is working.

**Comment by mikededo** [comment]
Hi @luv4ever2shail 😄 

I've also had some issues when running on Linux or in specific folder names in Windows such as `data`. Could you tell me what is your OS, and if it never works?

**Comment by luv4ever2shail** [comment]
I'm using macOs Big Sur

**Comment by mikededo** [comment]
I think there's a problem on activating the extension. I spent most of yesterday trying to fix it in Linux but I could not find the reason why it happens 😞 

If I cannot solve it, I will re-write the extension. Currently I'm a bit busy with university but as soon as I can I will get into it.

If you want to fork and make a pull request, feel free!

**Comment by mikededo** [comment]
Hey @luv4ever2shail :smile: 

I've migrated the extension from TS to JS. I wanted to see if I could do it with TypeScript but I guess I still have a long road to learn. So I decided to go back to JS, since I've coded more with it.

Before publishing the app, I have created a branch [Ts_to_js](https://github.com/mikededo/dartBarrelFileGenerator/tree/ts_to_js) where you can find the new/updated extension.

Could you plese clone the branch and try to run it in your MacOS? It would mean a lot to me! :1st_place_medal: 

Once you've told me that it works properly, I will make the final pushes and update it.

**Comment by luv4ever2shail** [comment]
Hey @mikededo 

I would love to test it out for you. But I have never created or ran a VSCode extension.
So could you please guide me through in order for me to test it out?

Thank you for looking into this. This is awesome.

**Comment by luv4ever2shail** [comment]
Hey @mikededo 

I was able to successfully run and test the project.
It works awesome.

Some problems:
- Option to generate barrel file was not able on the right click when I was testing (Is this normal?)
- When running the command current and nested folders on the **lib** doesn't seem to work
- Another issue is the barrel file is named after the folder name. Which wipes out the data of the file present with the same name in the folder. Can you to do check for that as well if possible?

Let me know if you need more testing done on this?

**Comment by mikededo** [comment]
Sorry! I was in class...

> I was able to clone and install all the npm dependencies but it just giving me error on the 'lodash' import. Any reason?

I'm glad you solved it!

> * Option to generate barrel file was not able on the right click when I was testing (Is this normal?)

Hmm 🤔, that is not normal. You could only do `Generate Current and Nested` option?

> * When running the command current and nested folders on the **lib** doesn't seem to work

I will give it a check. With the last version there where some times where the folder named `data` would not work. Did any error pop out? Was any file created? If so, was the file empty? Does this `lib` folder contain any `.dart` file (it only works if it has a `.dart` file as a **direct child**)?

> * Another issue is the barrel file is named after the folder name. Which wipes out the file contents present with the same name in the folder. Can you to do check for that as well if possible?

Well, I think it breaks it's philosohpy. Barrel files are intended to be named after the folder, that's is why it wipes out it's content. I do not intend to change it but maybe we'll see in the future 😉 

I've also seen that now I do not export the nested folders barrel file when using `Generate Current and Selected`. I will give a look now!

If you find anything, please, do not hesitate to update the code!

**Comment by luv4ever2shail** [comment]
> Hmm 🤔, that is not normal. You could only do Generate Current and Nested option?
>
I was not able to access the `Generate Current and Nested` option on right click during testing. (in fact none of the option was available on right click)

Regarding lib folder.. I didn't receive any error message.

Thank you

**Comment by mikededo** [comment]
That is strange. I can use both options... By the way, are you clicking in a folder, or in a file? The extension is set up only to work when clicked on a folder!

**Comment by mikededo** [comment]
Changes pushed and working in Windows and Linux!

**Comment by mikededo** [comment]
I'm closing this issue!

I've you encounter any error, just open a new one 😉

**Comment by pituJCD** [comment]
ajafja
