### ISSUE TITLE
Files with suffix same as folder are not included in barell file

### ISSUE THREAD

**Issue by petrnymsa** [mikededo/dartBarrelFileGenerator#10]
Following structure
```
modal/
├─ modal_header.dart
├─ single_modal.dart
├─ btn.dart
```
generated `modal.dart` contains
```dart
export 'btn.dart';
export 'modal_header.dart';
```

Any file which ends the same as the folder name is not included. Note that the folder's name as a prefix is ok.

**Comment by petrnymsa** [comment]
@mikededo  Hi, OS is Windows 10. 

I dig little into the code and the issue is with the following if statement within `shouldExport`

```
 if (posixPath.endsWith('.dart') && !posixPath.endsWith(`${dirName}.dart`)) {
```
So any name ending with "folder" name will be catched here.  Maybe directly compare given file is not equal to folder name could be enough?

**Comment by mikededo** [comment]
Definetely. I will try to find a solution with Regex, instead of simple string comparison.

Please, feel free to create a pull request if wanted 🔥

**Comment by mikededo** [comment]
I'm planning to add tests and improving how the extension is coded (maybe migrating it to Typescript). However, this fix will be in the next minor version.

**Comment by mikededo** [comment]
It has been fixed in #11. Could you please give me your feedback? 😃

**Comment by petrnymsa** [comment]
@petrnymsa  thanks for quick solution! Tried it locally and looks good to me :)

**Comment by mikededo** [comment]
Great. As of now I will post this patch. I will dig into it more when I have time for what will be v2!
