### ISSUE TITLE
Custom ignore files

### ISSUE THREAD

**Issue by jttuboi** [mikededo/dartBarrelFileGenerator#18]
Hi, first of all, thanks for your VSCode extension, it helps me a lot.

I looked at configurations in VSCode and I only have found 2 ignore files which you define it: *.freezed.dart and *.g.dart. I believe this ignores is because they use 'part' and 'part of' inside them, and you don't need to export the other file. So I'm using Bloc and now it uses 'part' and 'part of' and I don't use this generates barrel properly because of these files.

I think, instead of create one more option to ignore a file, is it possible to add a list of files/folders to ignore like as git ignore do?

Suggestion with real examples:

You can find this in VSCode>Settings>User>Commonly Used

![image](https://user-images.githubusercontent.com/376856/152633176-57e23d33-1333-45a4-a044-21ef1b8297f5.png)

![image](https://user-images.githubusercontent.com/376856/152633186-d52bb20a-0ac2-4a65-be1f-0e7b6fcb2e5f.png)

**Comment by mikededo** [comment]
Hello @jttuboi! 👋🏼 

It is definetely possible, and it is something I was waiting to be requested before made. I will be implementing such feature soon, if you feel like it could be something useful.

I'll keep you noticed 😉

**Comment by mikededo** [comment]
Alright! Changes made 😄 

I will release the feature in a couple of days, when I release the `v2.0.0` of the extension.

**Comment by mikededo** [comment]
The extension has been updated right now!
