### ISSUE TITLE
Need configuration to add files to ignore

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mikededo/dartBarrelFileGenerator#4]
I am working with mobx and it generates .g.dart files. I think it would be usefull to have a posibility to ignore them from barrel file.

**Comment by mikededo** [comment]
Good idea @vytautas-pranskunas-! I will try to add it as soon as possible.

If you feel like contribuiting, I will look forward to merging some PR! 💯

**Comment by mikededo** [comment]
What other generated filed do you think should be excluded?

I've thought of `.g.dart` and `.freezed.dart`

**Comment by vytautas-pranskunas-** [comment]
I think if you can add some ignore files array which can be modified then we do not have to think about all cases :)

**Comment by vytautas-pranskunas-** [comment]
I wish i have time for contributing :( But This feature would be super helpful ;)

**Comment by mikededo** [comment]
I've implemented test, where `.g.dart` and `.freezed.dart` are excluded by default (it can be changed in settings).

I look forward to adding the possibility of inserting an array of file extensions that should be excluded when generating the barrel file. What I fear is that, for instance, if the folder has many files and the user configuration array has many, many file extensions to ignore, it may take a bit of time to run the command.
However, it would be a very extreme case. 

I'll update the extension. I'll be glad if you could give me some feedback 😄

**Comment by vytautas-pranskunas-** [comment]
I will
