### ISSUE TITLE
Generate single file without generating in its sub folders

### ISSUE THREAD

**Issue by murataksuu** [mikededo/dartBarrelFileGenerator#56]
If I have a file directory like

```sh
lib/test1/example1.dart
lib/test2/example2.dart
lib/test3/example3.dart
lib/test4/example4.dart
```
 
Test directories contain only one file. For these, 4 files will be created: `test1.dart, test2.dart, test3.dart, test4.dart`.
 
It might be better to merge it into one file instead: `lib/<file-name>.dart`

**Comment by mikededo** [comment]
Thanks for opening an issue @murataksuu!

Hmm, I like what you are proposing. I could add a new option that would:

- Create a barrel file 🛢️ in the folder selected with all the exports from its nested folders.
- **Do not** create a barrel file on its nested folders.

What do you think?

**Comment by murataksuu** [comment]
It looks very good. We will be able to export our libraries containing many files in a single file in a short time. Without allowing confusion. Thank you

**Comment by mikededo** [comment]
I will try to work on it this weekend. I will keep you noticed 😃

**Comment by mikededo** [comment]
Feature added in `v4.0.0` which should be life now! Thank you for your proposal, give me any feedback you can 💪🏼!

Star the project and recommend it to your fellow developers to help the extension grow 😄

**Comment by murataksuu** [comment]
Wonderful! Thank you for your interest.
