### ISSUE TITLE
Not working with extensions

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mikededo/dartBarrelFileGenerator#6]
When trying to generate barel from extensions - barel file stays empty

```
extension Services on List<SelectListItem> {
  String toServicesString() {
    return this.map((e) => e.value).join('    ');
  }
}
```

**Comment by mikededo** [comment]
I do not understand what do you mean with it. Could you please be more specific? Could you provide an example where I can recreate it?

**Comment by mikededo** [comment]
I'm closing the issues since there's been no response 😉

**Comment by vytautas-pranskunas-** [comment]
If I have extensions file in the folder and run generator barel files stays empty

**Comment by mikededo** [comment]
Can you provide a folder example or something where I can generate such error?

**Comment by vytautas-pranskunas-** [comment]
I have provided file content. Create .dart file with code I pasted above
and try to run generator

**Comment by mikededo** [comment]
Sure. If tried using the following folder scheme:

```bash
test
└── main.dart
```

And after running the generator I get

```bash
test
├── main
└── test.dart
```

Where `test.dart` contains the `main.dart` export.

**Comment by vytautas-pranskunas-** [comment]
I will try to put more info soon

**Comment by vytautas-pranskunas-** [comment]
I am not sure what is happening but sometimes it does not work. e.g.
I had file in folder with commented code. I used generator for that folder all worked good. After i uncommented the code and new file is not added into barel file but generator says it has generated all succefully:

![image](https://user-images.githubusercontent.com/3918999/109635109-49bf4400-7b4a-11eb-814c-2683d293423e.png)
![image](https://user-images.githubusercontent.com/3918999/109635136-504dbb80-7b4a-11eb-8003-019ac8054c7f.png)
![image](https://user-images.githubusercontent.com/3918999/109635150-55ab0600-7b4a-11eb-8e34-66ba01fd910e.png)

as you can see items_list_helper
