### ISSUE TITLE
Use generator option on multiple diectories

### ISSUE THREAD

**Issue by saschaernst** [mikededo/dartBarrelFileGenerator#74]
Would it be possible to select multiple directories and execute the selected generator option on each one individually? It would save a lot of mouseclicks when taking care of lots of separate features in a project.

Sascha

**Comment by mikededo** [comment]
Hi @saschaernst!

It is something I have kept in mind for a while. I think it may take me some time to do it and I currently do not have such. Nonetheless, I try to do it or at least to find an acceptable solution.

As of now, I can only close the issue as I can't tell when this will be done! Sorry for the inconvenience but I will keep you noticed 😉
