### ISSUE TITLE
Option for putting generated file at the same level as target folder

### ISSUE THREAD

**Issue by drinkmorecola** [mikededo/dartBarrelFileGenerator#75]
Could it be possible to have the generated file like this?
```
models\
  course.dart\
  user.dart\
models.dart\ <- The generated file which exports models/course.dart and models/user.dart
```

This structure can make the import paths look better.
``` dart
import '../models.dart';
// or this if I only want the course model
import '../models/course.dart'
```

Btw this extension is really helpful to organise the files, especially in a big project. Nice work!

**Comment by mikededo** [comment]
Hi @drinkmorecola! Thanks for opening an issue 👋🏼!

There's the option `GDBF: Current with subfolders`. I have now seen that it is not documented in the readme!

Could you try it and see if it helps?

Thanks for the support!

**Comment by mikededo** [comment]
I'm closing the issue now as I'm not receiving any response! The option I have proposed it should produce the output you are looking for.

If there's any issue, reopen the issue!

**Comment by drinkmorecola** [comment]
Sorry for late reply. That result is a bit different from what I’m expecting. The generated file is in the target folder (E.g. the path of generated file in the example is `../models/models.dart`), but I want the path to be `../models.dart`, which means the `models.dart` is out of the `models` folder. They should be at the same level.

**Comment by mikededo** [comment]
Just something that I do not understand from your example: `course.dart` and `user.dart` are files or folders? The `/` at the end makes it confusing as normally folders are ended with the dash.

**Comment by drinkmorecola** [comment]
🙈they are files. Here’s the correct example.
```
models/
  course.dart
  user.dart
models.dart
```

**Comment by mikededo** [comment]
So `models.dart` is outside the `models/` folder?

**Comment by drinkmorecola** [comment]
Yes that’s what I mean.

**Comment by mikededo** [comment]
Does the `models` folder have a parent component?

If so, you can do:

1. In your settings, turn to `true` the `dartBarrelFileGenerator.promptName`. This will display an input when you are generating a barrel file.
2. Right click the parent folder and generate for the current with subfolders.
3. An input will show and ask you for a name. Enter the name you want (`models` in this case).

It should generate a barrel file outside the `models/` folder with the `models.dart` name.

Would that help you?

**Comment by drinkmorecola** [comment]
If there are more than one folder, for example
```
models/
  course.dart
  user.dart
services/
  service.dart
```
The generated `models.dart` will export files under `services`  too, which is unexpected.

**Comment by mikededo** [comment]
Yes, it will. I'm planning on also adding a feature that would allow you to exclude folders. As of now this is not possible.

I'm sorry but what you are asking for it is really complex to do, and I'm currently not with enough time to do it. I also have the feeling that this is a really ad-hoc case, so I would need to find a solution for many specific cases, therefore implementing complexity in the code. 🙏🏼 

Nonetheless, I would not recommend having barrel files outside the folder from they should be exported, as this breaks with the idea of why they exist.

I will close the issue but I will keep the idea in mind. Maybe if I have time enough I will try to find a solution...

**Comment by drinkmorecola** [comment]
Really appreciate your patience!
