### ISSUE TITLE
Exporting empty files

### ISSUE THREAD

**Issue by mrgnhnt96** [mikededo/dartBarrelFileGenerator#78]
There is an setting to exclude files and directories from being exported, which is helpful to omit from the export file, but the export file will still be generated even if there are no files to export.

Could we skip the file generation of the empty barrel files?

**Comment by mikededo** [comment]
Hi @mrgnhnt96! Thanks for opening an issue ⚡️

Yes! I believe it would be a nice addition. However, I will add a setting option that will let you choose in whether your want to skip empty barrel files or not (it will be set to true bu default, as it is what makes more sense). 

I will keep you updated

**Comment by mikededo** [comment]
Hi @mrgnhnt96!

Version `6.0.0` is on its way 🚀. It should be available in the following minutes, as the marketplace gets updated.

Please contact me if you find anything that is not to your liking! Consider starring the project and sharing it with your friends so it has more visibility! Thanks for your idea! 🙇‍♂️

**Comment by mrgnhnt96** [comment]
Thanks for doin this so quickly! Excited to start using the new feature!
