### ISSUE TITLE
Update command names

### ISSUE THREAD

**Issue by mrgnhnt96** [mikededo/dartBarrelFileGenerator#90]
I get confused (pretty frequently) which command performs which output. Specifically, `Current folder with nested folders` and `Current with subfolders`.

I wonder how this could be re-worded to provide better context?

`Current folder with nested folders` -> `Folders (Recursive)`
`Current folder only` -> `This Folder`
`Current with subfolders` -> `Folders' Files (Recursive)`

I'm open to suggestions!

**Comment by mikededo** [comment]
Hi @mrgnhnt96!

The new version is being deployed in the marketplace. Thank you for your patience!
